name: Maven CI for Selenium Test Automation

# When should this workflow run?
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use windows-latest if required
    
    # Define environment variables if needed
    env:
      CHROMEWEBDRIVER: /usr/local/bin/chromedriver  # Path to ChromeDriver on GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code in the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Install Maven dependencies
      run: mvn install -DskipTests  # Install the dependencies without running tests

    - name: Run Tests with Maven
      run: mvn clean test  # Run your test suite

    # This step will archive the test results and reports, including Extent Report
    - name: Archive test results
      if: always()  # Even if the tests fail, archive the reports
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/  # Adjust path if your reports are saved elsewhere

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-report
        path: extentReport.html  # Adjust this to the correct path of the report

